In [8]:
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\troy\\Documents\\Code\\Libraries', 
                 'C:\\Users\\troy\\Documents\\Excel Sheets', 'C:/Users/troy/Documents/Code/Libraries'])

%matplotlib qt

from PyEMD import EMD
from datetime import date, datetime
import numpy as np
import pandas as pd

import statsmodels.api as sm
import ipywidgets as widgets
import matplotlib.pyplot as plt

from tia.bbg import LocalTerminal
from FinAPI.NumerixWrapper import Base
from FinAPI.HistoricalData.HistoryManager import BloombergHistory

# Functions
def regress_out(asset_df):
    """
    regress the supplied factor from the asset dataframe

    :param asset_df:
    :return:
    """
    r = asset_df
    df = dict()
    for c in asset_df:
        if c!='USD':
            sub_df = r[[c, "USD"]]
            first_valid_index = sub_df.first_valid_index()
            working_df = sub_df.loc[first_valid_index:].fillna(0)
            x = np.array(working_df['USD'])
            y = np.array(working_df[c])
            x = sm.add_constant(x)
            model = sm.OLS(y, x)
            results = model.fit()
            slope = results.params[1]
            const = results.params[0]
            print('*****')
            print('%s vs USD' % c)
            print(results.params)
            print(results.rsquared)
            resid = y - const - slope * x[:, 1]
            df[c] = pd.Series(resid, index=working_df.index)
    return pd.DataFrame(df)


# History Setup
start_date = '1/1/2009'
end_date = date.today()
tickers = {'USD': ['USFS055 Curncy'],
           'CAD': ['CDFS0505 Curncy'],
           'EUR': ['SD0045FS 5Y5Y BLC Curncy'],
           'GBP': ['SD0022FS 5Y5Y BLC Curncy'],
           'CHF': ['SD0021FS 5Y5Y BLC Curncy'],
           'SEK': ['SD0020FS 5Y5Y BLC Curncy'],
           'JPY': ['SD0013FS 5Y5Y BLC Curncy'],
           'AUD': ['S0303FS 5Y5Y BLC Curncy'],
           'NZD': ['NDFS0505 Curncy'],
           'KRW': ['S0205FS 5Y5Y BLC Curncy'],
           'SGD' :['SDFS0505 Curncy'],
           'HKD' : ['HDFS0505 Curncy'],
           'TWD': ['S0203FS 5Y5Y BLC Curncy'],
           'THB': ['S0211FS 5Y5Y BLC Curncy'],
           'MYR': ['S0209FS 5Y5Y BLC Curncy'],
           'INR': ['S0266FS 5Y5Y BLC Curncy'],
           'CNH': ['S0204FS 5Y5Y BLC Curncy']
           }

bbg_tickers = []
column_names = []
for ccy in tickers:
    bbg_tickers = bbg_tickers+tickers[ccy]
    column_names.append(ccy)
resp = LocalTerminal.get_historical(bbg_tickers, 'PX_LAST', start=start_date, end=end_date)
raw_data_df = resp.as_frame()

# Clean data
analysis_df = raw_data_df.iloc[:len(raw_data_df)-1250, :]
ticker_ccy_map = dict(zip(bbg_tickers, column_names))
df_columns = [ticker_ccy_map[c] for c,v in analysis_df.columns.values]
analysis_df.columns = df_columns

# regress out USD
residual_df = regress_out(analysis_df)

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] on win32

In [4]:
analysis_df.head()

,CNH,USD,NZD,CAD,EUR,GBP,KRW,SGD,CHF,HKD,SEK,TWD,JPY,THB,MYR,AUD,INR
date,,,,,,,,,,,,,,,,,
2009-01-01,2.6377,3.0796,5.3350,3.4628,4.3166,3.8032,3.7974,2.5708,3.1850,1.8191,3.5160,1.5977,1.5385,2.3766,4.1933,4.5551,5.2331
2009-01-02,2.6377,3.2898,5.3350,3.6523,4.3658,3.8723,3.7874,2.6590,3.2675,1.9198,3.5138,1.5977,1.5785,2.3766,4.0505,4.4124,5.0238
2009-01-05,2.5320,3.4529,5.4094,3.7515,4.3479,3.9658,3.7366,2.7498,3.3444,2.1252,3.6660,1.6638,1.5813,2.4956,3.7241,4.7784,5.1296
2009-01-06,2.5792,3.3487,5.4412,3.7577,4.5030,4.0652,3.7065,2.9205,3.4767,2.4282,3.5794,1.8940,1.7182,2.7211,3.9439,4.6907,5.3886
2009-01-07,2.5454,3.3299,5.5208,3.8429,4.5688,4.0757,3.6844,2.9503,3.5637,2.4625,3.8301,1.7774,1.7138,3.0763,4.0557,4.7753,6.1580

In [9]:
residual_df.plot()

NameError: name 'residual_df' is not defined

In [52]:
rate_chg_df = residual_df.diff()
rate_chg_zscores = (rate_chg_df - rate_chg_df.mean()) / rate_chg_df.std()
rate_chg_zscores_ranges = pd.DataFrame({'Max': rate_chg_zscores.quantile(0.9925), 'Min': rate_chg_zscores.quantile(0.0075)})
rate_chg_df[np.abs(rate_chg_zscores)>3.5] = 0
rate_chg_df.iloc[0,:] = residual_df.iloc[0, :]
robust_resid_df = rate_chg_df.cumsum(axis=0)
robust_resid_df.plot()

In [65]:
ccy1 = 'USD'
ccy2 = 'HKD'

data = analysis_df[[ccy1, ccy2]]
either_or_holidays = data[np.isnan(data.USD) | np.isnan(data.HKD)].index

rebalance_freq = 60
rebalance = np.zeros(data.shape[0])